name: custom_dropdown_pro
description: Custom dropdown widget allows to add highly customizable dropdown widget in your projects with proper open and close animations. Features includes Search on list data, Network request search, Multi-selection and Form validation.
version: 3.1.1
homepage: https://github.com/Koleshy/custom-dropdown-pro

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:

funding:
  - https://buymeacoffee.com/koleshy

screenshots:
  - description: "Custom dropdown Preview"
    path: screenshots/preview.png
  - description: "Dropdown example"
    path: screenshots/example_1.jpg
  - description: "Search dropdown example"
    path: screenshots/example_2.jpg
  - description: "Multi select dropdown example"
    path: screenshots/example_3.jpg

topics:
  - ui
  - dropdown
  - spinner
  - widget
  - widgets

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows: